name: Generate terraform docs
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
      with:
        working-dir: .
        recursive: true
        output-file: README.md
        output-method: inject
        template: |-
          <!-- BEGIN_TF_DOCS -->
          {{ .Content }}

          ---
          <!-- END_TF_DOCS -->
        git-push: "true"
